"""Add is_active column to products table

Revision ID: 10bd1a54a71d
Revises: 
Create Date: 2024-09-24 23:27:09.938275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10bd1a54a71d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
