"""Add foreign key relationship

Revision ID: 258b6ad6ffff
Revises: bff930a9843d
Create Date: 2024-09-26 04:12:51.866003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "258b6ad6ffff"
down_revision = "bff930a9843d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("category")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.TEXT(),
            type_=sa.String(length=100),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "image_url",
            existing_type=sa.TEXT(),
            type_=sa.String(length=200),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "image_url",
            existing_type=sa.String(length=200),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    op.create_table(
        "category",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
