"""category table migration

Revision ID: bff930a9843d
Revises: f4b657434375
Create Date: 2024-09-26 03:58:57.735345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bff930a9843d"
down_revision = "f4b657434375"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("categories")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("category", sa.String(length=50), nullable=False)
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.TEXT(),
            type_=sa.String(length=100),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "image_url",
            existing_type=sa.TEXT(),
            type_=sa.String(length=200),
            existing_nullable=True,
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("category_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("category_id", sa.INTEGER(), nullable=False)
        )
        batch_op.create_foreign_key(
            None, "categories", ["category_id"], ["id"]
        )
        batch_op.alter_column(
            "image_url",
            existing_type=sa.String(length=200),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.drop_column("category")

    op.create_table(
        "categories",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
