"""Add email column to User model

Revision ID: f0a269622a4a
Revises: 10bd1a54a71d
Create Date: 2024-09-25 02:39:25.274505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0a269622a4a"
down_revision = "10bd1a54a71d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email", sa.String(length=120), nullable=False)
        )
        batch_op.create_unique_constraint("uq_users_email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_email", type_="unique")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
