"""Add image_url column to Product model

Revision ID: f4b657434375
Revises: f0a269622a4a
Create Date: 2024-09-25 23:58:40.924114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4b657434375"
down_revision = "f0a269622a4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_url", sa.String(length=200), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("image_url")

    # ### end Alembic commands ###
