name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8   # Using Python 3.8.16 to match local

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --max-line-length=100 .

      - name: Type check with mypy
        run: |
          pip install mypy
          mypy .

      - name: Check code formatting with black
        run: |
          pip install black==23.3.0
          black --check .
