# This workflow measures and reports test coverage of the FlourArtisansApp python codebase.
# It runs tests using pytest and generates a coverage report.

name: Test Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests and report coverage
        run: |
          pip install pytest coverage
          coverage run -m pytest
          coverage report
